name: ionbus

services:
  client:
    build:
      context: ../..
      dockerfile: docker/client/Dockerfile
    container_name: ionbus_client
    env_file:
      - ./cmd/server/.env
    depends_on:
      - client-mqtt-broker
    restart: unless-stopped

  client-mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    container_name: ionbus_client_mqtt
    env_file:
      - ./cmd/server/.env
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    restart: unless-stopped

volumes:
  rabbitmq_data:
  postgres_data:
  mqtt_data:
  mqtt_log: